name: Push

on:
  push:
    branches: [master]

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Push git tag
        run: |
          git config user.email "CI@bot.com"
          git config user.name "CI bot"
          git tag -a "v${{ steps.version.outputs.current-version }}" -m "Version ${{ steps.version.outputs.current-version }}"
          git push origin "v${{ steps.version.outputs.current-version }}"
