FROM node:24-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY .env ./
COPY vite.config.ts ./
COPY index.html ./
COPY src ./src
COPY public ./public

CMD ["npm", "start"]
